# -*- coding: utf-8 -*-
"""两级分类映射:把 awesome-selfhosted 的 83 个技术标签归并成
小白能懂的大类(无「杂项」)。供 build_dataset.py 导入。

GROUP_META:   大类顺序、图标、中文名
TAG_MAP:      英文原标签 -> (大类key, 中文小类名)
MISC_OVERRIDE: 原「杂项」软件名 -> (大类key, 中文小类名),逐个归类
"""

# 大类:key, 图标, 中文名(展示顺序即此列表顺序)
GROUP_META = [
    ("media", "📷", "媒体与影音"),
    ("comm", "💬", "通讯与社交"),
    ("docs", "📝", "笔记与文档"),
    ("web", "🌐", "建站与博客"),
    ("task", "✅", "任务与日程"),
    ("biz", "💰", "财务与商务"),
    ("files", "📁", "文件与备份"),
    ("read", "📚", "阅读与学习"),
    ("infra", "🖥️", "服务器与网络"),
    ("data", "📊", "数据与监控"),
    ("auto", "🏠", "自动化与物联网"),
    ("sec", "🔒", "安全与隐私"),
    ("dev", "🤖", "AI 与开发"),
    ("game", "🎮", "游戏"),
    ("life", "🍳", "生活与健康"),
    ("tools", "🛠️", "实用工具"),
]

# 英文原标签 -> (大类key, 中文小类名)
TAG_MAP = {
    "Analytics": ("data", "数据分析"),
    "Archiving and Digital Preservation (DP)": ("files", "归档与存档"),
    "Automation": ("auto", "自动化"),
    "Blogging Platforms": ("web", "博客平台"),
    "Booking and Scheduling": ("task", "预约与排期"),
    "Bookmarks and Link Sharing": ("read", "书签收藏"),
    "Calendar & Contacts": ("task", "日历与联系人"),
    "Communication - Custom Communication Systems": ("comm", "即时通讯"),
    "Communication - Email - Complete Solutions": ("comm", "邮件服务器"),
    "Communication - Email - Mail Delivery Agents": ("comm", "邮件收取"),
    "Communication - Email - Mail Transfer Agents": ("comm", "邮件投递"),
    "Communication - Email - Mailing Lists and Newsletters": ("comm", "邮件列表与订阅"),
    "Communication - Email - Webmail Clients": ("comm", "网页邮箱"),
    "Communication - IRC": ("comm", "IRC 聊天"),
    "Communication - SIP": ("comm", "网络电话"),
    "Communication - Social Networks and Forums": ("comm", "社交与论坛"),
    "Communication - Video Conferencing": ("comm", "视频会议"),
    "Communication - XMPP - Servers": ("comm", "XMPP 服务器"),
    "Communication - XMPP - Web Clients": ("comm", "XMPP 客户端"),
    "Community-Supported Agriculture (CSA)": ("biz", "社区农业"),
    "Conference Management": ("task", "会议管理"),
    "Content Management Systems (CMS)": ("web", "内容管理系统"),
    "Customer Relationship Management (CRM)": ("biz", "客户关系 CRM"),
    "Database Management": ("infra", "数据库管理"),
    "DNS": ("infra", "DNS 域名解析"),
    "Document Management - E-books": ("read", "电子书"),
    "Document Management - Institutional Repository and Digital Library Software": ("docs", "数字图书馆"),
    "Document Management - Integrated Library Systems (ILS)": ("docs", "图书馆系统"),
    "Document Management": ("docs", "文档管理"),
    "E-commerce": ("biz", "电商"),
    "Feed Readers": ("read", "RSS 订阅"),
    "File Transfer - Object Storage & File Servers": ("files", "对象存储"),
    "File Transfer - Peer-to-peer Filesharing": ("files", "P2P 共享"),
    "File Transfer - Single-click & Drag-n-drop Upload": ("files", "快速上传分享"),
    "File Transfer - Web-based File Managers": ("files", "网页文件管理"),
    "File Transfer & Synchronization": ("files", "文件同步网盘"),
    "Games": ("game", "游戏"),
    "Games - Administrative Utilities & Control Panels": ("game", "游戏服务器面板"),
    "Generative Artificial Intelligence (GenAI)": ("dev", "生成式 AI"),
    "Genealogy": ("life", "家谱族谱"),
    "Groupware": ("task", "协同办公"),
    "Health and Fitness": ("life", "健康与健身"),
    "Human Resources Management (HRM)": ("biz", "人力资源"),
    "Internet of Things (IoT)": ("auto", "物联网 IoT"),
    "Inventory Management": ("biz", "库存管理"),
    "Knowledge Management Tools": ("docs", "知识管理"),
    "Learning and Courses": ("read", "在线课程"),
    "Manufacturing": ("biz", "生产制造"),
    "Maps and Global Positioning System (GPS)": ("life", "地图与定位"),
    "Media Management": ("media", "影音管理"),
    "Media Streaming - Audio Streaming": ("media", "音乐流媒体"),
    "Media Streaming - Multimedia Streaming": ("media", "综合流媒体"),
    "Media Streaming - Video Streaming": ("media", "视频流媒体"),
    "Money, Budgeting & Management": ("biz", "记账理财"),
    "Network Utilities": ("infra", "网络工具"),
    "Note-taking & Editors": ("docs", "笔记与编辑"),
    "Office Suites": ("docs", "办公套件"),
    "Password Managers": ("sec", "密码管理"),
    "Pastebins": ("files", "代码/文本粘贴"),
    "Personal Dashboards": ("data", "个人仪表盘"),
    "Photo Galleries": ("media", "相册"),
    "Polls and Events": ("task", "投票与活动"),
    "Proxy": ("infra", "代理"),
    "Recipe Management": ("life", "菜谱"),
    "Remote Access": ("infra", "远程访问"),
    "Resource Planning": ("biz", "资源规划 ERP"),
    "Search Engines": ("read", "搜索引擎"),
    "Self-hosting Solutions": ("infra", "自托管方案"),
    "Software Development - API Management": ("dev", "API 管理"),
    "Software Development - Feature Toggle": ("dev", "功能开关"),
    "Software Development - IDE & Tools": ("dev", "开发工具"),
    "Software Development - Localization": ("dev", "本地化翻译"),
    "Software Development - Low Code": ("dev", "低代码"),
    "Software Development - Project Management": ("dev", "项目管理"),
    "Software Development - Testing": ("dev", "测试工具"),
    "Task Management & To-do Lists": ("task", "待办清单"),
    "Ticketing": ("task", "工单系统"),
    "Time Tracking": ("task", "时间跟踪"),
    "URL Shorteners": ("files", "短链接"),
    "Video Surveillance": ("sec", "视频监控"),
    "Web Servers": ("infra", "Web 服务器"),
    "Wikis": ("docs", "Wiki 百科"),
}

# 原「杂项」软件 -> (大类key, 中文小类名),逐个归类,不留杂项
MISC_OVERRIDE = {
    "2FAuth": ("sec", "双因素认证"),
    "Anchr": ("tools", "网络小工具"),
    "Anubis": ("infra", "防护与防火墙"),
    "asciinema": ("dev", "开发工具"),
    "Baby Buddy": ("life", "育儿记录"),
    "ClipCascade": ("tools", "剪贴板同步"),
    "Cloudlog": ("life", "业余无线电"),
    "ConvertX": ("tools", "格式转换"),
    "CUPS": ("infra", "打印服务"),
    "CyberChef": ("dev", "加解密工具"),
    "Digiboard": ("docs", "协作白板"),
    "Digicard": ("tools", "图形制作"),
    "Digicut": ("media", "音视频剪辑"),
    "Digiface": ("tools", "头像生成"),
    "Digiflashcards": ("read", "记忆卡片"),
    "Digimerge": ("media", "音视频合成"),
    "Digiquiz": ("read", "在线测验"),
    "Digiread": ("read", "网页净化阅读"),
    "Digisteps": ("read", "教学路径"),
    "Digitranscode": ("media", "音视频转码"),
    "Digiview": ("media", "无干扰视频"),
    "Digiwords": ("tools", "词云生成"),
    "DOCAT": ("dev", "文档托管"),
    "Domain Locker": ("infra", "域名管理"),
    "DOMJudge": ("dev", "编程竞赛"),
    "ESMira": ("data", "问卷与研究"),
    "F-Droid": ("dev", "应用仓库"),
    "Flyimg": ("tools", "图片处理"),
    "Geeftlist": ("life", "礼物清单"),
    "google-webfonts-helper": ("dev", "字体自托管"),
    "Habitica": ("task", "习惯养成"),
    "HortusFox": ("life", "植物管理"),
    "ImgCompress": ("tools", "图片处理"),
    "Infisical Community Edition": ("sec", "密钥管理"),
    "iSponsorBlockTV": ("media", "广告拦截"),
    "IT-Tools by sharevb": ("dev", "开发工具"),
    "Jelu": ("read", "读书记录"),
    "jetlog": ("life", "飞行记录"),
    "Kasm Workspaces": ("infra", "云端工作区"),
    "Keygen": ("dev", "软件授权"),
    "Koillection": ("life", "藏品管理"),
    "LanguageTool": ("docs", "语法校对"),
    "Libre Translate": ("dev", "翻译 API"),
    "LubeLogger": ("life", "车辆保养"),
    "mosparo": ("sec", "垃圾防护"),
    "Movary": ("media", "观影记录"),
    "Neko": ("tools", "云端浏览器"),
    "OmniTools": ("dev", "开发工具"),
    "Open-Meteo": ("data", "天气数据"),
    "OpenReader": ("read", "文档朗读"),
    "OpenZiti": ("infra", "零信任网络"),
    "Operational.co": ("data", "告警时间线"),
    "penpot": ("dev", "设计原型"),
    "POMjs": ("sec", "密码生成"),
    "Pønskelisten": ("life", "心愿清单"),
    "Reactive Resume": ("docs", "简历制作"),
    "RemoteUtilities": ("infra", "远程支持"),
    "revealjs": ("docs", "幻灯片演示"),
    "Revive Adserver": ("biz", "广告投放"),
    "SANE Network Scanning": ("infra", "扫描仪共享"),
    "ScreenConnect": ("infra", "远程支持"),
    "string.is": ("dev", "字符串工具"),
    "Teleport": ("infra", "安全访问网关"),
    "TeslaMate": ("data", "车辆数据"),
    "URL-to-PNG": ("dev", "网页截图"),
    "Usertour": ("biz", "用户引导"),
    "Warracker": ("life", "保修追踪"),
    "Wavelog": ("life", "业余无线电"),
    "WeeWX": ("data", "气象站"),
    "WeTTY": ("infra", "网页终端"),
    "Wishlist": ("life", "心愿清单"),
    "Yamtrack": ("media", "媒体追踪"),
    "Zero-TOTP": ("sec", "双因素认证"),
}

GROUP_KEYS = {k for k, _, _ in GROUP_META}


def classify(name, tags):
    """返回 (group_key, sub_zh)。优先杂项覆盖表,其次首个命中的标签,
    都没有则归「实用工具/其他」(理论上不会触发)。"""
    if name in MISC_OVERRIDE:
        return MISC_OVERRIDE[name]
    for tag in tags:
        if tag in TAG_MAP:
            return TAG_MAP[tag]
    return ("tools", "其他")
